services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    platform: linux/arm64
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: fastapi_backend
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:8000"
    networks:
      - app_network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.redis_worker
    container_name: redis_worker
    command: python worker.py
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - redis
    networks:
      - app_network
networks:
  app_network:
    driver: bridge