services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    platform: linux/arm64

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    container_name: fastapi_backend
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
      platforms:
        - linux/arm64
    container_name: streamlit_frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"